services:
  db:
    container_name: postgres_report
    image: postgres:16.3
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    restart: always
    ports:
      - "5436:5432"

  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4:8.10
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_DEFAULT_EMAIL=mckamilo@gmail.com
    restart: always